<a href="https://colab.research.google.com/github/airmon1101/ML_Journey-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mylist = [1, 2, 3]

In [ ]:
type(mylist)

list

In [ ]:
myarr = np.array(mylist)

In [ ]:
type(myarr)

numpy.ndarray

In [ ]:
# Create metrix
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.arange(0, 10, 1) #(start, end, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create a 5,3 zeros matrix
np.zeros((5, 3)) # You must use --> (())

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Create 3,5 ones metrix
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Using linspace (np.linspace provide evenly spaced values)
np.linspace(0, 10, 11) #(start, stop, quantity)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Create a identity matrix OR square matrix using NumPy
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Create a random matrix
random_matrix = np.random.rand(5,5)

# Use np.set_printoptions to set the precision
np.set_printoptions(precision=2)

random_matrix

array([[0.77, 0.94, 0.6 , 0.7 , 0.1 ],
       [0.66, 0.26, 0.42, 0.15, 0.19],
       [0.16, 0.06, 0.18, 0.58, 0.39],
       [0.91, 0.09, 0.98, 0.07, 0.68],
       [0.53, 0.03, 0.21, 0.06, 0.88]])

In [ ]:
# set_printoption to 2
np.set_printoptions(precision=2)
# Create a vector using np,random.randn
np.random.randn(5)

array([-0.39,  0.15,  1.4 ,  0.34,  0.5 ])

In [ ]:
# Create a 2,3 matrix using random.randn
np.random.randn(2, 3)

array([[-0.16,  2.59, -0.48],
       [ 1.13, -0.21,  0.24]])

In [ ]:
# Print 10 random int numbers using np.random.randint()
print(np.random.randint(0, 101, 10)) # (start, stop, enter how many number you want)

[  8  69 100  56  38  57   6  67  24  61]


In [ ]:
# Create a 5,5 matrix using random.randint
# np.random.randint(100) # get a random number
np.random.randint(0, 25,(5, 5)) #(start, end, (shape of a matrix = 5,5))

array([[24,  8, 15, 19, 24],
       [15,  1, 14, 12, 23],
       [22,  8, 15, 10, 11],
       [ 8,  3,  6, 23,  7],
       [19,  1, 10, 14,  3]])

In [ ]:
# Use this seed so you can produce exact same numbers like me
np.random.seed(42) # random.seed only works in same cell
np.random.rand(10)

array([0.37, 0.95, 0.73, 0.6 , 0.16, 0.16, 0.06, 0.87, 0.6 , 0.71])

In [ ]:
# Example this is a another cell
# Write the same code without random seed function
np.random.rand(10)

array([0.61, 0.14, 0.29, 0.37, 0.46, 0.79, 0.2 , 0.51, 0.59, 0.05])

In [ ]:
# Create a array using arange() function
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Reshape this arr using .reshape() function
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Create a random array using this randint() function
ranarr = np.random.randint(0, 101, 10)
ranarr

array([50,  6, 20, 72, 38, 17,  3, 88, 59, 13])

In [ ]:
# Find the maximum value in this array using .max() function
ranarr.max()

np.int64(88)

In [ ]:
# Find the maximum value element index location in array using armax() function
ranarr.argmax()

np.int64(7)

In [ ]:
# Find the minimum value in this array using .min() function
ranarr.min()

np.int64(3)

In [ ]:
# Find the minimum value element index location in a array using argmin() function
ranarr.argmin()

np.int64(6)

In [ ]:
# Check dtype of an array using .dtype
ranarr.dtype
print(f" ranarr = {ranarr} \n lenth of ranarr = {len(ranarr)} \n size of ranarr = {ranarr.size} \n maximum value in ranarr = {ranarr.max()} \n index of maximum value in ranarr = {ranarr.argmax()} \n ranarr data type = {ranarr.dtype} \n minimum value in ranarr = {ranarr.min()} \n index of maximum value in ranarr = {ranarr.argmin()} \n ")

 ranarr = [50  6 20 72 38 17  3 88 59 13] 
 lenth of ranarr = 10 
 size of ranarr = 10 
 maximum value in ranarr = 88 
 index of maximum value in ranarr = 7 
 ranarr data type = int64 
 minimum value in ranarr = 3 
 index of maximum value in ranarr = 6 
 


In [ ]:
# 1D vector
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Reshape = 5,5 and reassigned
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Reshape = 1,25 and reassigned
# !!! --> Note this process add an extra dimension in this array
arr = arr.reshape(1, 25)
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
# Reshape = 25,1 and reassigned
# !!! --> Note this process add an extra dimension in this array
arr = arr.reshape(25, 1)
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

Indexing and selection in NumPy

*   Grabbing single element
*   Grabbing a slice of elements
*   Broadcasting selection
*   Indexing and selection in 2-dimensions
*   Conditional Selection



In [ ]:
import numpy as np

In [ ]:
# Grabbing single element
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# print(arr[6])
# OR
arr[6]

np.int64(6)

In [ ]:
arr[1:5] #[start=1:end=5-1]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]# [start=0(start_default=0):end=5-1]
# OR
# arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5]# [start=0(start_default=0):end=5-1]
# OR
# arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]# [start=5:end=Last_Element]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# Broadcasting
# OR
# Reassing values of an array
arr[0:5] = 300
arr

array([300, 300, 300, 300, 300,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset this array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arr[0:5] #OR arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
# Its share's same memory location
slice_of_arr[:3] = 200
slice_of_arr, arr

(array([200, 200, 200,   3,   4]),
 array([200, 200, 200,   3,   4,   5,   6,   7,   8,   9,  10]))

In [ ]:
# Reset this array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Use .copy() to resolve this issue
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Broadcasting of an array
arr_copy[2:8] = 100
# Problem solved
arr_copy, arr

(array([  0,   1, 100, 100, 100, 100, 100, 100,   8,   9,  10]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# indexing in 2D array
